# Generated by Django 3.0.8 on 2020-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='default_bg.jpeg', upload_to='background_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_dp.png', upload_to='profile_pics'),
        ),
    ]
