# Generated by Django 3.0.8 on 2020-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Summary', max_length=200),
            preserve_default=False,
        ),
    ]
